Projeto Bilheteira/Models/Movie_Session.cs
namespace Utad_Proj_.Models
{
    using System;
    using System.ComponentModel.DataAnnotations;
    using Utad_Proj_.Models;

    public class Movie_Session
    {
        [Required]
        [Display(Name = "Date")]
        [DataType(DataType.DateTime)]
        public DateTime Date_ { get; set; }

        public int Id { get; set; }
        public Movie Movie { get; set; }
        public int MovieID { get; set; }
        public Room Room { get; set; }
        public int RoomID { get; set; }
    }
}

Projeto Bilheteira/Controllers/Movie_SessionController.cs
namespace Utad_Proj_.Controllers
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Threading.Tasks;
    using Microsoft.AspNetCore.Mvc;
    using Microsoft.AspNetCore.Mvc.Rendering;
    using Microsoft.EntityFrameworkCore;
    using Utad_Proj_.Data;
    using Utad_Proj_.Models;

    public class Movie_SessionController : Controller
    {
        private readonly ApplicationDbContext _context;

        public Movie_SessionController(ApplicationDbContext context)
        {
            _context = context;
        }

        [HttpGet, ActionName("BeginTicketsPurchaseIntent")]
        public async Task<IActionResult> BeginTicketsPurchaseIntent(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var room = await _context.Sessions
                .Include(x => x.Room)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (room == null)
            {
                return NotFound();
            }

            return View(room);
        }

        // GET: Movie_Session/Create
        public IActionResult Create()
        {
            ViewData["MovieID"] = new SelectList(_context.Movies, "Id", "Title");
            ViewData["RoomID"] = new SelectList(_context.Rooms, "Id", "Name");
            return View();
        }

        // POST: Movie_Session/Create To protect from overposting attacks, enable the specific
        // properties you want to bind to. For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Date_,MovieID,RoomID")] Movie_Session movie_Session)
        {
            if (ModelState.IsValid)
            {
                _context.Add(movie_Session);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["MovieID"] = new SelectList(_context.Movies, "Id", "Title", movie_Session.MovieID);
            ViewData["RoomID"] = new SelectList(_context.Rooms, "Id", "Name", movie_Session.RoomID);
            return View(movie_Session);
        }

        // GET: Movie_Session/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var movie_Session = await _context.Sessions
                .Include(m => m.Movie)
                .Include(m => m.Room)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (movie_Session == null)
            {
                return NotFound();
            }

            return View(movie_Session);
        }

        // POST: Movie_Session/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var movie_Session = await _context.Sessions.FindAsync(id);
            _context.Sessions.Remove(movie_Session);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        // GET: Movie_Session/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var movie_Session = await _context.Sessions
                .Include(m => m.Movie)
                .Include(m => m.Room)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (movie_Session == null)
            {
                return NotFound();
            }

            return View(movie_Session);
        }

        // GET: Movie_Session/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var movie_Session = await _context.Sessions.FindAsync(id);
            if (movie_Session == null)
            {
                return NotFound();
            }
            ViewData["MovieID"] = new SelectList(_context.Movies, "Id", "Title", movie_Session.MovieID);
            ViewData["RoomID"] = new SelectList(_context.Rooms, "Id", "Name", movie_Session.RoomID);
            return View(movie_Session);
        }

        // POST: Movie_Session/Edit/5 To protect from overposting attacks, enable the specific
        // properties you want to bind to. For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Date_,MovieID,RoomID")] Movie_Session movie_Session)
        {
            if (id != movie_Session.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(movie_Session);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!Movie_SessionExists(movie_Session.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["MovieID"] = new SelectList(_context.Movies, "Id", "Title", movie_Session.MovieID);
            ViewData["RoomID"] = new SelectList(_context.Rooms, "Id", "Name", movie_Session.RoomID);
            return View(movie_Session);
        }

        // GET: Movie_Session
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.Sessions.Include(m => m.Movie).Include(m => m.Room);
            return View(await applicationDbContext.ToListAsync());
        }

        private bool Movie_SessionExists(int id)
        {
            return _context.Sessions.Any(e => e.Id == id);
        }
    }
}

Projeto Bilheteira/Controllers/RoomsController.cs
namespace Utad_Proj_.Controllers
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Threading.Tasks;
    using Microsoft.AspNetCore.Identity;
    using Microsoft.AspNetCore.Mvc;
    using Microsoft.AspNetCore.Mvc.Rendering;
    using Microsoft.EntityFrameworkCore;
    using Utad_Proj_.Data;
    using Utad_Proj_.Models;
    using Utad_Proj_.Services;
    using Utad_Proj_.ViewModel;

    public class RoomsController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly IPurchaseService purchaseService;
        private readonly UserManager<ApplicationUser> userManager;

        public RoomsController(
            ApplicationDbContext context,
            IPurchaseService purchaseService,
            UserManager<ApplicationUser> userManager)
        {
            _context = context;
            this.purchaseService = purchaseService;
            this.userManager = userManager;
        }

        [HttpGet, ActionName("CheckOut")]
        [Route("CheckOut")]
        public async Task<IActionResult> CheckOut(
                    [FromQuery] int movieSessionId,
                    [FromQuery] int numberOfTickets,
                    [FromQuery] float price)
        {
            Movie_Session movieSession = await this._context.Sessions
                .Include(x => x.Movie)
                .Include(x => x.Room)
                .FirstOrDefaultAsync(x => x.Id == movieSessionId)
                .ConfigureAwait(false);

            string userId = this.userManager.GetUserId(this.User);

            PurchaseIntentViewModel purchaseIntent = new PurchaseIntentViewModel
            {
                ApplicationUserId = userId,
                MovieTitle = movieSession.Movie.Title,
                MovieSessionId = movieSessionId,
                NumberOfTickets = numberOfTickets,
                Price = price,
                RoomName = movieSession.Room.Name,
                Date = movieSession.Date_
            };
            return View(purchaseIntent);
        }

        [HttpPost, ActionName("ConfirmPurchase")]
        [Route("ConfirmPurchase")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> ConfirmPurchase(PurchaseIntentViewModel purchaseIntent)
        {
            await this.purchaseService.CreatePurchaseAsync(new CreatePurchaseArgs
            {
                ApplicationUserId = purchaseIntent.ApplicationUserId,
                Date = purchaseIntent.Date,
                MovieSessionId = purchaseIntent.MovieSessionId,
                Price = purchaseIntent.Price
            }).ConfigureAwait(false);

            return RedirectToAction("Index", "Movies");
        }

        // GET: Rooms/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Rooms/Create To protect from overposting attacks, enable the specific properties
        // you want to bind to. For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,Num")] Room room)
        {
            if (ModelState.IsValid)
            {
                _context.Add(room);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(room);
        }

        // GET: Rooms/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var room = await _context.Rooms
                .FirstOrDefaultAsync(m => m.Id == id);
            if (room == null)
            {
                return NotFound();
            }

            return View(room);
        }

        // POST: Rooms/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var room = await _context.Rooms.FindAsync(id);
            _context.Rooms.Remove(room);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        // GET: Rooms/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var room = await _context.Rooms.FindAsync(id);
            if (room == null)
            {
                return NotFound();
            }
            return View(room);
        }

        // POST: Rooms/Edit/5 To protect from overposting attacks, enable the specific properties
        // you want to bind to. For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,Num")] Room room)
        {
            if (id != room.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(room);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!RoomExists(room.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(room);
        }

        // GET: Rooms
        public async Task<IActionResult> Index()
        {
            return View(await _context.Rooms.ToListAsync());
        }

        private bool RoomExists(int id)
        {
            return _context.Rooms.Any(e => e.Id == id);
        }
    }
}

Projeto Bilheteira/Views/Movie_Session/BeginTicketsPurchaseIntent.cshtml
@model Utad_Proj_.Models.Movie_Session

@{
    ViewData["Title"] = "Purchase Tickets";
    var i = 0;
}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <title>Movie Seat Booking</title>
    <link rel="stylesheet" href="/Tickets/TicketsStyle.css">
    
    <style>
      
    </style>
  </head>
  <body>
    
    

     
    <div class="movie-container">
      <label style="font-size: 1em;">Ticket Price:</label>
      <select id="movie">
        <option value="10">$10</option>

      </select>
    </div>

    <ul class="showcase">
      <li>
        <div id="seat" class="seat"></div>
        <small class="status" style="font-size: 1em;">N/A</small>
      </li>
      <li>
        <div id="seat" class="seat selected"></div>
        <small class="status" style="font-size: 1em;">Selected</small>
      </li>
      <li>
        <div id="seat" class="seat occupied"></div>
        <small class="status" style="font-size: 1em;">Occupied</small>
      </li>
    </ul>

    
     <div class="container">
      <div class="screen"></div>

          <div class="row" >
              @for(i=0; i <= Model.Room.Num; i++)
            {
                  <div id="seat" class="seat"></div>
            }
        </div>



    </div>
    

    <p class="text" style="font-size: 1em;margin:0px 0px 15px 0px">
      You have selected <span id="count">0</span> seats for a price of $<span
        id="total"
        >0</span
      >
    </p>

    <a href="/Movies">
      <button class="btn-home">
        Home
      </button>
    </a>
        
      <button class="btn-home" style="float: right;" onclick="buyTicketsOnClick();">
        Comprar Bilhete(s)
      </button>


    <!--
        .
        Count  = numero de lugares comprados.
        Total  = numero de euros vai ter que pagar.
        .
    -->
    <script>
        
     
      var count=0;
      var totalPrice=0;
      var seats=document.getElementsByClassName("seat");
      for(var i=0;i<seats.length;i++){
        var item=seats[i];
        
        item.addEventListener("click",(event)=>{
          var price= document.getElementById("movie").value;

          if (!event.target.classList.contains('occupied') && !event.target.classList.contains('selected') ){
          count++;
          
          totalPrice=count*price;
          event.target.classList.add("selected");
          document.getElementById("count").innerText=count;
          document.getElementById("total").innerText=totalPrice;

          //document.write(count);
          }
        })
      }

      function buyTicketsOnClick(){
          var urlToCheckout = '@Url.Action("CheckOut", "Rooms")'
            + '?movieSessionId=' + '@Model.Id'
            + '&numberOfTickets=' + count
            + '&price=' + totalPrice;

          window.location.href = urlToCheckout;
      }
    </script>
  </body>
</html>


<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Projeto Bilheteira/Views/Movie_Session/Create.cshtml
@model Utad_Proj_.Models.Movie_Session

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Movie_Session</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Date_" class="control-label"></label>
                <input asp-for="Date_" class="form-control" />
                <span asp-validation-for="Date_" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="MovieID" class="control-label"></label>
                <select asp-for="MovieID" class ="form-control" asp-items="ViewBag.MovieID"></select>
            </div>
            <div class="form-group">
                <label asp-for="RoomID" class="control-label"></label>
                <select asp-for="RoomID" class ="form-control" asp-items="ViewBag.RoomID"></select>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Projeto Bilheteira/Views/Movie_Session/Delete.cshtml
@model Utad_Proj_.Models.Movie_Session

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Movie_Session</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Date_)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Date_)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Movie)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Movie.Title)
        </dd class>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Room)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Room.Name)
        </dd class>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Projeto Bilheteira/Views/Movie_Session/Details.cshtml
@model Utad_Proj_.Models.Movie_Session

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Movie_Session</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Date_)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Date_)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Movie)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Movie.Title)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Room)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Room.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Room.Num)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Room.Num)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Projeto Bilheteira/Views/Movie_Session/Edit.cshtml
@model Utad_Proj_.Models.Movie_Session

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Movie_Session</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Date_" class="control-label"></label>
                <input asp-for="Date_" class="form-control" />
                <span asp-validation-for="Date_" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="MovieID" class="control-label"></label>
                <select asp-for="MovieID" class="form-control" asp-items="ViewBag.MovieID"></select>
                <span asp-validation-for="MovieID" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="RoomID" class="control-label"></label>
                <select asp-for="RoomID" class="form-control" asp-items="ViewBag.RoomID"></select>
                <span asp-validation-for="RoomID" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Projeto Bilheteira/Views/Movie_Session/Index.cshtml
@model IEnumerable<Utad_Proj_.Models.Movie_Session>

@{
    ViewData["Title"] = "Index";


}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<ul>
<table class="table table-striped table-bordered">

     
    @foreach (var item in Model.GroupBy(p => p.Movie.Title))
    {
        <thead>
            <tr>
                
                <th>
                    @item.Key
                </th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item1 in item)
            {
                <tr>
                    <td>@item1.Date_</td>
                    <td>@item1.Room.Name</td>
                    <td>
                    @if (User.IsInRole("Admin") || User.IsInRole("Employee")  )   {<a asp-action="Delete" asp-route-id="@item1.Id">Delete</a>}|
                    @if (User.IsInRole("Admin") || User.IsInRole("Employee")  )   {<a asp-action="Edit" asp-route-id="@item1.Id">Edit</a>}|   
                    <a asp-action="Details" asp-route-id="@item1.Id">Details</a> |
                    <a asp-controller="Movie_Session" asp-action="BeginTicketsPurchaseIntent" asp-route-id="@item1.Id"><button class="btn-home">Comprar Bilhete(s)</button></a> 
            </td>
                </tr>
            }
        </tbody>
        <tfoot>

        </tfoot>
    }

</table>