Projeto Bilheteira/Controllers/MoviesController.cs
namespace Utad_Proj_.Controllers
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Text;
    using System.Threading.Tasks;
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Http;
    using Microsoft.AspNetCore.Mvc;
    using Microsoft.AspNetCore.Mvc.Rendering;
    using Microsoft.EntityFrameworkCore;
    using Utad_Proj_.Data;
    using Utad_Proj_.Models;
    using Utad_Proj_.Services;

    public class MoviesController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly IEmailSenderService emailSenderService;
        private readonly NewMovieEmailSenderOptions newMovieEmailSenderOptions;

        public MoviesController(ApplicationDbContext context,
            IEmailSenderService emailSenderService,
            NewMovieEmailSenderOptions newMovieEmailSenderOptions)
        {
            _context = context;
            this.emailSenderService = emailSenderService;
            this.newMovieEmailSenderOptions = newMovieEmailSenderOptions;
        }

        public static List<SelectListItem> GetDropDownListForYears()
        {
            List<SelectListItem> ls = new List<SelectListItem>();

            for (int i = 1920; i <= DateTime.Now.Year; i++)
            {
                ls.Add(new SelectListItem() { Text = i.ToString(), Value = i.ToString() });
            }

            return ls;
        }

        [Authorize(Roles = "Admin, Employee")]
        public IActionResult Create()
        {
            ViewData["CategoryID"] = new SelectList(_context.Categories, "Id", "Name");
            return View();
        }

        // POST: Movies/Create To protect from overposting attacks, enable the specific properties
        // you want to bind to. For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Title,year,description,trailer,cast,photo,CategoryID")] Movie movie)
        {
            if (Request.Form.Files.Count > 0)
            {
                IFormFile file = Request.Form.Files.FirstOrDefault();
                using (var dataStream = new MemoryStream())
                {
                    await file.CopyToAsync(dataStream);
                    movie.photo = dataStream.ToArray();
                }
            }
            if (ModelState.IsValid)
            {
                _context.Add(movie);
                int affectedRecords = await _context.SaveChangesAsync().ConfigureAwait(false);

                if (affectedRecords > 0)
                {
                    var allUsers = await this._context.Users.ToListAsync().ConfigureAwait(false);
                    var category = await this._context.Categories.FirstOrDefaultAsync(x => x.Id == movie.CategoryID).ConfigureAwait(false);

                    var contentBuilder = new StringBuilder();
                    contentBuilder.AppendLine("New movie released:")
                        .AppendLine()
                        .AppendLine($"* Title: {movie.Title}")
                        .AppendLine($"* Year: {movie.year}")
                        .AppendLine($"* Category: {category.Name}")
                        .AppendLine()
                        .AppendLine("Thank you.");
                    string content = contentBuilder.ToString();

                    foreach (var user in allUsers)
                    {
                        await this.emailSenderService.SendEmailAsync(new SendEmailArgs
                        {
                            HtmlContent = content,
                            ReceiverEmail = user.Email,
                            ReceiverName = user.UserName,
                            SenderEmail = this.newMovieEmailSenderOptions.SenderEmail,
                            SenderName = this.newMovieEmailSenderOptions.SenderName,
                            Subject = "New movie released"
                        }).ConfigureAwait(false);
                    }
                }

                return RedirectToAction(nameof(Index));
            }
            ViewData["CategoryID"] = new SelectList(_context.Categories, "Id", "Name", movie.CategoryID);
            return View(movie);
        }

        [Authorize(Roles = "Admin, Employee")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var movie = await _context.Movies
                .Include(m => m.Category)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (movie == null)
            {
                return NotFound();
            }

            return View(movie);
        }

        // GET: Movies/Delete/5
        // POST: Movies/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var movie = await _context.Movies.FindAsync(id);
            _context.Movies.Remove(movie);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        // GET: Movies/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var movie = await _context.Movies
                .Include(m => m.Category)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (movie == null)
            {
                return NotFound();
            }

            return View(movie);
        }

        [Authorize(Roles = "Admin, Employee")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var movie = await _context.Movies.FindAsync(id);
            if (movie == null)
            {
                return NotFound();
            }
            var moviemodel = new MovieEdit();
            moviemodel.Id = movie.Id;
            moviemodel.Title = movie.Title;
            moviemodel.description = movie.description;
            moviemodel.year = movie.year;
            moviemodel.photo = movie.photo;
            moviemodel.cast = movie.cast;
            moviemodel.trailer = movie.trailer;
            moviemodel.CategoryID = movie.CategoryID;
            ViewData["CategoryID"] = new SelectList(_context.Categories, "Id", "Name", movie.CategoryID);
            return View(movie);
        }

        // POST: Movies/Edit/5 To protect from overposting attacks, enable the specific properties
        // you want to bind to. For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, MovieEdit model)
        {
            if (id != model.Id)
            {
                return NotFound();
            }

            if (Request.Form.Files.Count > 0)
            {
                IFormFile file = Request.Form.Files.FirstOrDefault();
                using (var dataStream = new MemoryStream())
                {
                    await file.CopyToAsync(dataStream);
                    model.photo = dataStream.ToArray();
                }
            }
            var movie = await _context.Movies.FindAsync(id);
            movie.Title = model.Title;
            movie.year = model.year;
            if (model.photo != null)
                movie.photo = model.photo;
            movie.cast = model.cast;
            movie.CategoryID = model.CategoryID;
            movie.description = model.description;
            movie.trailer = model.trailer;
            movie.cast = model.cast;

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(movie);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!MovieExists(movie.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["CategoryID"] = new SelectList(_context.Categories, "Id", "Name", movie.CategoryID);
            return View(movie);
        }

        // GET: Movies
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.Movies.Include(m => m.Category);
            return View(await applicationDbContext.ToListAsync());
        }

        private bool MovieExists(int id)
        {
            return _context.Movies.Any(e => e.Id == id);
        }
    }
}

Projeto Bilheteira/Views/Shared/_CommentBox.cshtml
@model Utad_Proj_.ViewModel.ArticleCommentViewModel
<dl class="dl-horizontal">
    <dt>
        Comment
    </dt>
    <dd>
        <div class="commentBox">
            @using (Html.BeginForm("Add", "ArticleComments", FormMethod.Post, new { onsubmit = "return SubmitComment()" })) 
            {
                @Html.AntiForgeryToken()
                <div class="form-horizontal">
                    <div class="form-group">
                        <label class="col-md-4 control-label">
                            Your rating <span style="font-weight:normal;">(1 star is horrible, 10 star is excelent)</span>
                        </label>
                        <div class="col-md-7">
                            <div onmouseout="CRateSelected()">
                                <span class="starFade" id="Rate1" onclick="CRate(1)" onmouseover="CRateOver(1)" onmouseout="CRateOut(1)">

                                </span><span class="starFade" id="Rate2" onclick="CRate(2)" onmouseover="CRateOver(2)" onmouseout="CRateOut(2)"></span>

                                <span class="starFade" id="Rate3" onclick="CRate(3)" onmouseover="CRateOver(3)" onmouseout="CRateOut(3)">

                                </span><span class="starFade" id="Rate4" onclick="CRate(4)" onmouseover="CRateOver(4)" onmouseout="CRateOut(4)"></span>

                                <span class="starFade" id="Rate5" onclick="CRate(5)" onmouseover="CRateOver(5)" onmouseout="CRateOut(5)"></span>
                                <span class="starFade" id="Rate6" onclick="CRate(6)" onmouseover="CRateOver(6)" onmouseout="CRateOut(6)"></span>
                                <span class="starFade" id="Rate7" onclick="CRate(7)" onmouseover="CRateOver(7)" onmouseout="CRateOut(7)"></span>
                                <span class="starFade" id="Rate8" onclick="CRate(8)" onmouseover="CRateOver(8)" onmouseout="CRateOut(8)"></span>
                                <span class="starFade" id="Rate9" onclick="CRate(9)" onmouseover="CRateOver(9)" onmouseout="CRateOut(9)"></span>
                                <span class="starFade" id="Rate10" onclick="CRate(10)" onmouseover="CRateOver(10)" onmouseout="CRateOut(10)"></span>

                            </div>
                        </div>
                    </div>
                
                <div class="from-group">
                    <div class="col-md-12">
                        <textarea asp-for="Comment"  requiredrows="10" style="width:100%;" class="form-control"></textarea>
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-12">
                        <input type="hidden" asp-for="ArticlesId" />
                        <input type="hidden" name="Rating" id="Rating" value="0" />
                        <input type="submit" id="btnRegister" name="btnRegister" value="Submit Comment" class="btn btn-warning" />
                    </div>
                </div>
           </div>
            }
        </div>
        </dd>
</dl>
<script>
	function SubmitComment() {
	if ($("Rating#").val() == "0"){
            alert("Please rate this service provider.");
            return false;}
	else{
		return true;
	}
}

	function CRate(r) {
		$("Rating#").val(r);
		for(var i = 1; i <= r; i++){
			$("Rate#" + i).attr('class', 'starGlow');
		} 		
		for(var i = r + 1; i <= 5; i++){
			$("Rate#" + i).attr('class', 'starFade');
		}
} 

	function CRateOver(r) {
		for(var i = 1; i <= r; i++){
		$("Rate#" + i).attr('class', 'starGlow');
		} 
}

	function CRateOut(r) {
		for(var i = 1; i <= r; i++){
		$("Rate#" + i).attr('class', 'starFade');
		} 
}

	function CRateSelected() {
		var setRating = $("Rating#").val();
		for(var i = 1; i <= setRating; i++){
		$("Rate#" + i).attr('class', 'starGlow');
		} 
}
</script>

Projeto Bilheteira/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<ApplicationUser> SignInManager

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Utad_Proj_</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    @if(Context.Request.Cookies["viewMode"] == "dark")
    {
        <link rel="stylesheet" href="~/css/site_dark.css" />
    }
    else
    {
        <link rel="stylesheet" href="~/css/site.css" />
    }
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Movies" asp-action="Index">Webcinema</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Movies" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Movies" asp-action="Index">Movies</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Purchases" asp-action="Index">MyTickets</a>
                        </li>
                        @if (User.IsInRole("Admin"))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Admin" asp-action="Index">Manage</a>
                            </li>
                        }
                        @if (SignInManager.IsSignedIn(User))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Preferences">Preferences</a>
                            </li>
                        }
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Articles" asp-action="Index">Forum</a>
                        </li>

                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
 
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>